// Generated by gencpp from file dt_test_pkg/ControlEvalResponse.msg
// DO NOT EDIT!


#ifndef DT_TEST_PKG_MESSAGE_CONTROLEVALRESPONSE_H
#define DT_TEST_PKG_MESSAGE_CONTROLEVALRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dt_test_pkg
{
template <class ContainerAllocator>
struct ControlEvalResponse_
{
  typedef ControlEvalResponse_<ContainerAllocator> Type;

  ControlEvalResponse_()
    : control_ok(false)  {
    }
  ControlEvalResponse_(const ContainerAllocator& _alloc)
    : control_ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _control_ok_type;
  _control_ok_type control_ok;





  typedef boost::shared_ptr< ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ControlEvalResponse_

typedef ::dt_test_pkg::ControlEvalResponse_<std::allocator<void> > ControlEvalResponse;

typedef boost::shared_ptr< ::dt_test_pkg::ControlEvalResponse > ControlEvalResponsePtr;
typedef boost::shared_ptr< ::dt_test_pkg::ControlEvalResponse const> ControlEvalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator1> & lhs, const ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator2> & rhs)
{
  return lhs.control_ok == rhs.control_ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator1> & lhs, const ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dt_test_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f3e17e0aaa02da7d620767756fd89dc";
  }

  static const char* value(const ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f3e17e0aaa02da7ULL;
  static const uint64_t static_value2 = 0xd620767756fd89dcULL;
};

template<class ContainerAllocator>
struct DataType< ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dt_test_pkg/ControlEvalResponse";
  }

  static const char* value(const ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#CREATE response parameters\n"
"\n"
"bool control_ok\n"
;
  }

  static const char* value(const ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control_ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlEvalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dt_test_pkg::ControlEvalResponse_<ContainerAllocator>& v)
  {
    s << indent << "control_ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.control_ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DT_TEST_PKG_MESSAGE_CONTROLEVALRESPONSE_H
