// Generated by gencpp from file dt_test_pkg/ControlEval.msg
// DO NOT EDIT!


#ifndef DT_TEST_PKG_MESSAGE_CONTROLEVAL_H
#define DT_TEST_PKG_MESSAGE_CONTROLEVAL_H

#include <ros/service_traits.h>


#include <dt_test_pkg/ControlEvalRequest.h>
#include <dt_test_pkg/ControlEvalResponse.h>


namespace dt_test_pkg
{

struct ControlEval
{

typedef ControlEvalRequest Request;
typedef ControlEvalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ControlEval
} // namespace dt_test_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dt_test_pkg::ControlEval > {
  static const char* value()
  {
    return "958048232c806861307e0b0592b4443c";
  }

  static const char* value(const ::dt_test_pkg::ControlEval&) { return value(); }
};

template<>
struct DataType< ::dt_test_pkg::ControlEval > {
  static const char* value()
  {
    return "dt_test_pkg/ControlEval";
  }

  static const char* value(const ::dt_test_pkg::ControlEval&) { return value(); }
};


// service_traits::MD5Sum< ::dt_test_pkg::ControlEvalRequest> should match
// service_traits::MD5Sum< ::dt_test_pkg::ControlEval >
template<>
struct MD5Sum< ::dt_test_pkg::ControlEvalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dt_test_pkg::ControlEval >::value();
  }
  static const char* value(const ::dt_test_pkg::ControlEvalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dt_test_pkg::ControlEvalRequest> should match
// service_traits::DataType< ::dt_test_pkg::ControlEval >
template<>
struct DataType< ::dt_test_pkg::ControlEvalRequest>
{
  static const char* value()
  {
    return DataType< ::dt_test_pkg::ControlEval >::value();
  }
  static const char* value(const ::dt_test_pkg::ControlEvalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dt_test_pkg::ControlEvalResponse> should match
// service_traits::MD5Sum< ::dt_test_pkg::ControlEval >
template<>
struct MD5Sum< ::dt_test_pkg::ControlEvalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dt_test_pkg::ControlEval >::value();
  }
  static const char* value(const ::dt_test_pkg::ControlEvalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dt_test_pkg::ControlEvalResponse> should match
// service_traits::DataType< ::dt_test_pkg::ControlEval >
template<>
struct DataType< ::dt_test_pkg::ControlEvalResponse>
{
  static const char* value()
  {
    return DataType< ::dt_test_pkg::ControlEval >::value();
  }
  static const char* value(const ::dt_test_pkg::ControlEvalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DT_TEST_PKG_MESSAGE_CONTROLEVAL_H
